services:
  - type: web
    name: your-bot-name-here
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: python main.py
